@url = http://localhost:4444
@identity_provider = http://localhost:8080
@campaign_id = {{campaign_create.response.body.id}}

###
GET {{url}}/ping

###
# @name campaign_create
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "Name": "change",
    "Content": "Change password",
    "Emails": ["pamella@email.com", "bruno@email.com", "josi@email.com","aline@email.com"]
}

###

GET {{url}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

PATCH {{url}}/campaigns/cancel/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

Patch {{url}}/campaigns/start/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

Delete {{url}}/campaigns/delete/{{campaign_id}}
Authorization: Bearer {{access_token}}

###

# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=pamella&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}